"use client"

import { useEffect, useState } from "react"
import Head from "next/head";
import { useRouter } from "next/router";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  useRouter()

  const [isloaded, setIsloaded] = useState(false)
  useEffect(() => {
    setIsloaded(true)
  }, [])

  return (

            <html lang="en">
              <body >
                <Head>
                  <title>Online</title>
                  <meta name="description" content="Generated by create next app" />
                  <link rel="icon" href="/favicon.ico" />
                </Head>
              </body>
            </html>
        
  )
}
