# Generated by Django 4.2.2 on 2023-06-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mvp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="image",
            field=models.ImageField(upload_to="complaints"),
        ),
        migrations.AlterField(
            model_name="user",
            name="token",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
