import type { AppProps } from 'next/app'
import '../styles/globals.css'
import Head from "next/head";
import Script from "next/script";
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import { AllUsersContext } from '../src/context/allusers';
import { UserInterface } from '../src/interfaces/user';


function MyApp({ Component, pageProps }: AppProps) {
  const [allUsers, setAllUsers] = useState<UserInterface[]>([])
  const router = useRouter()
  const [mounted, setMounted] = useState(false)
  useEffect(() => {
    setMounted(true)
    if (localStorage.getItem('user') == null) {
      router.push('login')

    }
    if (localStorage.getItem('allUsers') != null) {
      setAllUsers(JSON.parse(localStorage.getItem('allUsers')!) as UserInterface[]  )

    }
  }, [])
  const update = (value: UserInterface[]) => {
    setAllUsers(value)
  }
  return <AllUsersContext.Provider value={{
    update: update,
    value: allUsers
  }}>
    <>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Online Management System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossOrigin="anonymous" />

      </Head>

      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossOrigin="anonymous" />
      {
        mounted == true ? <Component {...pageProps} /> : <></>
      }

    </>
  </AllUsersContext.Provider>
}

export default MyApp
