# Generated by Django 4.2.2 on 2023-06-21 08:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0004_alter_complaint_latitude_alter_complaint_longitude"),
    ]

    operations = [
        migrations.RenameField(
            model_name="complaint",
            old_name="user_id",
            new_name="user",
        ),
    ]
