# Generated by Django 4.2.2 on 2023-06-21 08:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0005_rename_user_id_complaint_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="complaint",
            old_name="user",
            new_name="user_id",
        ),
    ]
