# Generated by Django 4.2.2 on 2023-06-21 08:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0006_rename_user_complaint_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="complaint",
            old_name="user_id",
            new_name="user",
        ),
    ]
