# Generated by Django 4.2.2 on 2023-06-21 09:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0007_rename_user_id_complaint_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="status",
        ),
    ]
