# Generated by Django 4.2.2 on 2023-06-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0008_remove_complaint_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("in_progress", "in_progress"),
                    ("completed", "completed"),
                ],
                default="pending",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
