# Generated by Django 4.2.2 on 2023-06-21 09:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restapi", "0009_complaint_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="complaint_id",
            new_name="complaint",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="reward",
            old_name="complaint_id",
            new_name="complaint",
        ),
        migrations.RenameField(
            model_name="reward",
            old_name="user_id",
            new_name="user",
        ),
    ]
