# Generated by Django 4.2.2 on 2023-06-27 06:58

import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mvp_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="image",
            field=models.ImageField(
                storage=core.storage_backends.PublicMediaStorage(), upload_to=""
            ),
        ),
    ]
