# Generated by Django 4.2.2 on 2023-07-10 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("mvp_api", "0002_comment_updated_at_alter_complaint_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="complaint",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="mvp_api.complaint",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="description",
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="latitude",
            field=models.FloatField(default="0.0", editable=False),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="longitude",
            field=models.FloatField(default="0.0", editable=False),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="title",
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="user",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="token",
            field=models.IntegerField(default=0),
        ),
    ]
