# Generated by Django 4.2.2 on 2023-07-13 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("mvp_api", "0003_alter_comment_complaint_alter_comment_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="complaint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mvp_api.complaint"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="latitude",
            field=models.FloatField(default="0.0"),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="longitude",
            field=models.FloatField(default="0.0"),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
